import type { NextConfig } from "next";

const securityHeaders = [
  { key: "X-Frame-Options", value: "DENY" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
];

const nextConfig: NextConfig = {
  async headers() {
    return [{ source: "/(.*)", headers: securityHeaders }];
  },
  // The icon is generated by app/icon.tsx, and a favicon cannot be code-generated
  // (Next app-icons docs). Modern browsers follow the emitted <link rel="icon">,
  // but crawlers and link-preview tools still probe /favicon.ico directly — map
  // it to the generated PNG rather than serving them a 404.
  async rewrites() {
    return [{ source: "/favicon.ico", destination: "/icon" }];
  },
};

export default nextConfig;
